spring:
  application:
    name: gateway

  data:
    mongodb:
      uri: ${MONGO_URI}

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      routes:
        - id: hotel-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/hotels/**

        - id: booking-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/bookings/**

server:
  port: ${PORT:8080}