spring:
  application:
    name: gateway
  data:
    mongodb:
      uri: ${MONGO_URI}
  cloud:
    gateway:
      routes:
        - id: hotel_management
          uri: https://hotel-management-doxv.onrender.com
          predicates:
            - Path=/api/v1/**

#        - id: booking-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/v1/bookings/**

# CORS Configs
cors:
  allowed-origins:
    - http://localhost:4200
    - https://sach-cp.github.io

# JWT configs
security:
  jwt:
    secret-key: YuizCKebQrK8OXhBTEeKOAaTQFY1xIeNtlDfygjA/Ko=
    expiration-time: 3600000
